name: tokokita
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.11

flutter:
  uses-material-design: true
